# Trauma - only up to date maps are in the default pool
- type: gameMapPool
  id: DefaultMapPool
  maps:
  #- Atlas
  #- Amber
  #- Bagel
  #- Box
  #- Cluster
  - Fland
  - FlandHighPop
  - Loop
  #- Marathon
  #- Meta
  #- Oasis
  #- OasisHighPop
  #- Omega
  - Origin
  #- Saltern
  #- Packed
  #- Barratry
  #- Kettle
  #- Submarine
  - Leonid
  #- Delta
  #- Chloris
  - Cog
  #- Serpentcrest
